In [1]:
import pandas as pd
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [2]:
df.shape

(284807, 31)

In [7]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [35]:
#### Independent and dependent features
X = df.drop('Class',axis=1)
y=df.Class

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.7, random_state=0)

In [37]:
y_test.shape

(85443,)

### Cross validation like  KFold and hyperparameter tuning

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [57]:
log_class = LogisticRegression()
# Hyperparameter Tuning,
grid = {'C':10.0**np.arange(-2,3),'penalty':['l2']}
# Grid Search CV
cv = KFold(n_splits=5, random_state=None, shuffle=False)

In [58]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro',error_score='raise')
clf.fit(X_train,y_train)

C:\python37\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             error_score='raise', estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l2']},
             scoring='f1_macro')

In [71]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85253    43]
 [   46   101]]
0.9989583699074237
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.70      0.69      0.69       147

    accuracy                           1.00     85443
   macro avg       0.85      0.84      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [77]:
345*100

34500

In [76]:
y_train.value_counts()

0    199019
1       345
Name: Class, dtype: int64

In [78]:
class_weight = dict({0:1,1:100})

In [79]:
from sklearn.ensemble import RandomForestClassifier
# class_weight apply only if you have more number of values
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [80]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85292     4]
 [   38   109]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.96      0.74      0.84       147

    accuracy                           1.00     85443
   macro avg       0.98      0.87      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [73]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85290     6]
 [   35   112]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.95      0.76      0.85       147

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## Under Sampling
use this only if your dataset is very less so iam not gonna use this technique in this dataset

In [85]:
from collections import Counter
Counter(y_train)

Counter({0: 199019, 1: 345})

In [195]:
from collections import Counter
from imblearn.under_sampling import NearMiss
from sklearn.datasets import make_classification
ns = RandomUnderSampler(random_state=0)

In [212]:
X_train_ns,y_train_ns = ns.fit_resample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))

the number of classes before fit Counter({1: 900, 0: 100})
the number of classes after fit Counter({0: 100, 1: 100})


In [218]:
from sklearn.ensemble import RandomForestClassifier
# class_weight apply only if you have more number of values
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test,  y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

## Over Sampling

In [154]:
from imblearn.over_sampling import RandomOverSampler
os = RandomOverSampler(0.5)

X_train_os,y_train_os = os.fit_resample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_os)))

the number of classes before fit Counter({1: 900, 0: 100})
the number of classes after fit Counter({1: 900, 0: 450})


C:\python37\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [150]:
from sklearn.ensemble import RandomForestClassifier
# class_weight apply only if you have more number of values
classifier = RandomForestClassifier()
classifier.fit(X_train_os,y_train_os)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

## SMOTETomek

In [188]:
from imblearn.combine import SMOTETomek

In [189]:
os = SMOTETomek(0.5)

X_train_ns,y_train_ns = ns.fit_resample(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))

the number of classes before fit Counter({1: 900, 0: 100})
the number of classes after fit Counter({1: 142, 0: 100})


C:\python37\lib\site-packages\imblearn\utils\_validation.py:586: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [190]:
from sklearn.ensemble import RandomForestClassifier
# class_weight apply only if you have more number of values
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))